### ISSUE TITLE
Lexicon bugs - Low Priority

### ISSUE THREAD

**Issue by johnysandels** [karashiiro/TextToTalk#37]
-custom lexicon sometimes stops being used and uses default pronunciation.

-with a custom lexicon selected, sometimes TTS can't read anything out loud at all.

-with custom lexicon, sometimes voice gets stuck on one voice, and changing the voice crashes the game.
   -one time this happened the game kept crashing until I deleted my config. didn't happen again after.

First two issues can be fixed by deleting and reinstalling the plugin.

I haven't been able to test if any of this has been fixed in 1.8.0.1 because of /echo chat not working as mentioned in #36

**Comment by johnysandels** [comment]
Updated list with more issues

**Comment by karashiiro** [comment]
These all seem to be bugs and design choices in the .NET speech synthesizer, I'm looking into workarounds, probably going to do something hacky like this: https://stackoverflow.com/a/59035660/14226597. In the meantime, I'm pushing this to release with a disclaimer.

**Comment by karashiiro** [comment]
New: Renaming the file crashes the game.

**Comment by johnysandels** [comment]
Here is are two lexicons using pronemes for testing purposes. FFXIVen alters two game names (Alphinaud & Urianger) to their proper pronunciation. The second one is a test lexicon from the lexicon Wikipedia which I've altered, the words `test` and `text` should be pronounced as `apple` The word `dog` should pronounced as `cat`.  Both work in Amazon Polly and also work in the plugin when using Amazon Polly as a backend. 

Also both lexicon files work in all English languages in both the Amazon Polly website and also as a backend in the plugin. (tested for British and US) `xml:lang="en"` allows it to work for any english language, which doesn't currently work with the system backend, you must pick a region.

**Comment by karashiiro** [comment]
Leaving this here for my own reference: https://stackoverflow.com/a/642314

**Comment by karashiiro** [comment]
I think it's fair at this point to say that the native backend sucks, but I think I might've fixed some of these issues in https://github.com/goatcorp/DalamudPlugins/pull/1012.

**Comment by karashiiro** [comment]
Even with this, using the `phoneme` element just breaks things randomly.

**Comment by johnysandels** [comment]
Found as issue with how the standard plugin receives ipa formatting. Reading pronemes breaks TTS and makes it not say anything when using a regular colon,`:`. You need to use this special colon `ː` to make it work currently. Using spaces in pronemes also currently breaks the TTS and makes it not say anything. So avoiding spaces and using that special colon as a work around seems to be make Pronemes work after update 1.8.4.0. 

Spaces and regular colons work in Amazon Polly currently.

**Comment by karashiiro** [comment]
Updated the PR with replacements for those two issues.

**Comment by johnysandels** [comment]
Just caught another one, I didn't think you'd be so quick!. This Symbol `-` also should be working but currently isn't.

**Comment by johnysandels** [comment]
Seems like there's an issue with using the grapheme `Y'shtola`. Using a proneme with it cuases silence, using an alias with pronounces it with default pronunciation. 

The pronunciation for the word works if triggered with a different word (I used `Yshtola` with no apostrophe for testing and the pronunciation worked. So i can confrim it's not a problem with IPA symbols in pronemes). 

I remember Y'stola worked for with `<alias>` in the past, so something must have interacted with that somehow since then, since it doesn't work with proneme or alias.

**Comment by karashiiro** [comment]
Can you send a copy of the lexicon you're using for that? The main issue is that I'm reimplementing lexicon processing myself, and I only implemented the `grapheme` and `phoneme` nodes. If you have an `alias` node in your lexicon, I need to know how it's formatted so I can parse it out and use it.

**Comment by johnysandels** [comment]
[Lexicon Alias.zip](https://github.com/karashiiro/TextToTalk/files/6997773/Lexicon.Alias.zip) 
This uses Aliases for pronunciation. basically just trying to force pronunciation by using words.
example:
```
<lexeme>
   <grapheme>Bob</grapheme>
   <alias>Robert</alias>
</lexeme>
```
I mainly used this Wikipedia Article for help with lexicon xml formatting
https://en.wikipedia.org/wiki/Pronunciation_Lexicon_Specification
<br>
[Lexicon Proneme.zip](https://github.com/karashiiro/TextToTalk/files/6997784/Lexicon.Proneme.zip)
Pronemes use IPA format instead for more precise and non-region specific pronunciation.

Until recently Aliases were working to force pronunciation of words including everything in that first file. I actually just realized they're no longer working. Everything on that second file works now perfectly, except for Y'shtola, which was working fine on that first file earlier.

**Comment by karashiiro** [comment]
Should be fixed in https://github.com/goatcorp/DalamudPlugins/pull/1015

**Comment by karashiiro** [comment]
That was actually an unrelated fix to handle phoneme tags like this: `<phoneme alphabet="x-sampa" ph='m@"hA:g@%ni:'>mahogany</phoneme>` which have a double quote in the middle, but I reverted that and updated the PR so we can see if that caused issues.

**Comment by johnysandels** [comment]
Yeah I just tested it and nothing has seemed to change. Alias still works, and pronemes still don't. So sorry about the confusion!

**Comment by karashiiro** [comment]
Out of curiosity, does it work if you remove the lexeme with the `'s` grapheme? I think it's applying both that and the `Y'shtola` grapheme at the same time, so it ends up becoming
```
<phoneme ph="jiʃtoʊla">Y<phoneme ph="z">htola</phoneme></phoneme>
```
I don't know if that causes problems or not, but it might?

**Comment by johnysandels** [comment]
Yeah Using a config without 's makes Y'shtola work in 1.8.4.0! to clarify, in 1.8.5.0 all pronemes don't work at all.

**Comment by karashiiro** [comment]
How about now, I removed support for the `alphabet` attribute. That's the only other phoneme-related change I made, so maybe that's the issue?

I'm trying to make it work but it's less simple to keep track of where replacements have already occurred.

**Comment by johnysandels** [comment]
That fixed it 👍

**Comment by karashiiro** [comment]
The input text just has replacements run over it once for each grapheme-phoneme pair. I might've implemented a fix, updated PR.

**Comment by johnysandels** [comment]
![image](https://user-images.githubusercontent.com/79720646/129789300-e5f82a18-fdb2-4fd4-a367-2b7985a9a4ae.png)
TTS either doesn't work or it crashes the game

**Comment by karashiiro** [comment]
Random guess, apostrophes are reserved in the SSML specification [according to the Polly documentation](https://docs.aws.amazon.com/polly/latest/dg/escapees.html) (but it should be generally true), which is what's actually causing the issue. This also makes text containing `&` fail to generate speech. PR updated, and try using `&apos;` instead of `'` in the lexicon when you try it.

**Comment by johnysandels** [comment]
I am getting a that same crash from my last comment seemingly randomly and it seems like all of the in game text with an apostrophes in them don't use the lexicon anymore.

**Comment by karashiiro** [comment]
Undid that and handling SSML reserved tokens very differently now, it's messy but I think this should work correctly now.

**Comment by johnysandels** [comment]
Not boding well so far. the very first one I tested crashed the game. I typed `/echo G'raha` 
This is my code for that lexeme
```
	<lexeme>
		<grapheme>G'raha</grapheme>
		<phoneme>grɑhɑ</phoneme>
	</lexeme>
```
I've also tried it like this:
```
	<lexeme>
		<grapheme>G&apos;raha</grapheme>
		<phoneme>grɑhɑ</phoneme>
	</lexeme>
```

Is this how it is formatted in my lexicon file.

Some of the lexemes are working and some crash the game. I know Y'shtola is working, but Alisaie crashed the game too.

**Comment by karashiiro** [comment]
Alright, I reverted it to how it was when it was working (I think), I'll try digging deeper into this tomorrow.

**Comment by johnysandels** [comment]
Also this was in the dalamud.log 
```
2021-08-17 23:26:01.639 -04:00 [FTL] Unhandled exception on AppDomain
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at TextToTalk.Backends.System.LexiconManager.MakeSsml(String text, String langCode)
   at TextToTalk.Backends.System.SystemSoundQueue.OnSoundLoop(SystemSoundQueueItem nextItem)
   at TextToTalk.Backends.SoundQueue`1.PlaySoundLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by karashiiro** [comment]
Oh, duh, that explains a lot. One minute, I'm deploying a fix for that.

**Comment by karashiiro** [comment]
Actually, nevermind, that throws a major wrench into how I was doing it, I need to rethink how I'm preventing nested replacements again. I'll leave it at how it was before I tried fixing it for now.
