### ISSUE TITLE
Installation fails on Mac systems

### ISSUE THREAD

**Issue by 0xChief** [karashiiro/TextToTalk#83]
So the XIV on Mac launcher has support for Dalamud which is how I'm attempting to install TextToTalk

On Mac, I get the `failed to install plugin error. Please restart your game and try again` error. I can install other plugins but TTS won't ever work. 

Has anyone had any success with getting TTS on Mac for FF14?

**Comment by karashiiro** [comment]
Seems the issue is that it's trying to load the System (Windows) voice synthesizer the first time it's installed, so it instantly fails. I'll release a fix later tonight.

**Comment by karashiiro** [comment]
Should be fixed, now.

**Comment by 0xChief** [comment]
Bumping this to mention that I still get the failure to install message. Same situation, using XIV on Mac and attempting to install TextToTalk.
